sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker pull node:10-alpine
  - docker build -t rso9/auth .
  - docker run -d -p 127.0.0.1:80:3000 rso9/auth
  - docker ps -a

script:
  - npm test
