sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

env:
  - DOCKER_IMAGE=rso9/auth:0.1

before_install:
  - docker pull node:10-alpine
  - docker build -t "$DOCKER_IMAGE" .
  - docker run -d -p 127.0.0.1:80:3000 "$DOCKER_IMAGE"
  - docker ps -a

script:
  - npm test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
