apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: auth
          image: rso9/auth:0.6
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 2
          env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: rso9
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: auth
  type: LoadBalancer
