apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 7
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: auth
    spec:
      containers:
        - name: auth
          image: rso9/auth:0.1
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    name: auth
  type: LoadBalancer
